# Generated by Django 3.2 on 2021-04-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=16)),
                ('current_value', models.FloatField()),
                ('max_value', models.IntegerField()),
                ('sweep_type', models.CharField(choices=[('C', 'Continuous'), ('D', 'Discrete')], default='C', max_length=1)),
            ],
        ),
    ]
