# Generated by Django 3.2 on 2021-04-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210417_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('serial_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pedal',
            name='guitars',
            field=models.ManyToManyField(to='main_app.Guitar'),
        ),
    ]
